"""add boards and scores

Revision ID: e7c7f7916afa
Revises: 'b3dd921816fe'
Create Date: 2026-09-01 15:52:24.882630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7c7f7916afa'
down_revision: Union[str, None] = 'b3dd921816fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('SCORE', 'RATING', name='boardtype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('sort_direction', sa.Enum('DESC', 'ASC', name='sortdirection', native_enum=False, create_constraint=True, length=10), nullable=False),
    sa.Column('aggregation', sa.Enum('BEST', 'LAST', name='aggregation', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'key', name='uq_board_game_key')
    )
    op.create_index(op.f('ix_boards_game_id'), 'boards', ['game_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('board_id', 'idempotency_key', name='uq_score_board_idempotency')
    )
    op.create_index('ix_score_board_player_value', 'scores', ['board_id', 'player_id', 'value'], unique=False)
    # ### end Alembic commands ###

    # Every existing game keeps its 1v1 rating leaderboard, now expressed as a board.
    # Without this the rating becomes unreachable: GET /leaderboard is gone and
    # GET /boards/rating/top has nothing to resolve.
    op.execute(
        """
        INSERT INTO boards (game_id, key, name, type, sort_direction, aggregation, created_at)
        SELECT id, 'rating', 'Rating', 'RATING', 'DESC', 'BEST', now()
        FROM games
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_score_board_player_value', table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_boards_game_id'), table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###