"""add display_name to players

Revision ID: f8e9345f03e4
Revises: 'b33d29ed3dd5'
Create Date: 2026-07-30 21:47:26.865814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e9345f03e4'
down_revision: Union[str, None] = 'b33d29ed3dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('display_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'display_name')
    # ### end Alembic commands ###